FROM node:18
ARG BUILD_CONTEXT
# Create app directory
WORKDIR /usr/src/app

COPY ./$BUILD_CONTEXT/ .
COPY yarn.lock .

RUN yarn install

# Bundle app source
# COPY . .

EXPOSE 3005
CMD [ "yarn", "start" ]