FROM node:18 as build

# Create app directory
WORKDIR /usr/src/app

COPY . .
ENV NODE_OPTIONS "--max-old-space-size=8192"
RUN yarn install
EXPOSE 3000
ENV REACT_APP_PROXY_URL="https://staging-console-proxy.akash.network/"
ENV REACT_APP_PROXY_WSS="wss://staging-console-proxy.akash.network"
CMD ["yarn", "start"]